language: c

env:
  global:
    - PACKAGE_NAME="ocveralls"
    - PACKAGE_URL="https://github.com/sagotch/ocveralls.git"
    - OPAM_DEPENDS="ocamlfind ounit bisect ocveralls"
  matrix:
    - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0

install: curl -s https://raw.githubusercontent.com/sagotch/travis-ocaml/0.1.0/travis-ocaml.sh | bash

script:
  - eval `opam config env`
  - make coverage coveralls

notifications:
  email: false
